//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.11
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub a1ebb8b8-5600-4df3-93d1-8843eb18604c aws-my-sample-app-android-v0.11";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("ap-northeast-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "ap-northeast-1:a37ee634-cb6b-4907-a8c5-3b8bde076801";
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("ap-northeast-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "ap-northeast-1_SjYsPPFLQ";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "917kcrpbvn04ggfepa8buu7oa";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "lgrjc489tfq39uuk70bqgta21o6r9eg8hsmg5tra8slj9l81p4b";
}
